blueprint: api.yml
color: true
config: ./dredd.yml
custom: {}
details: false
dry-run: null
endpoint: 'http://localhost'
header: []
hookfiles: null
hooks-worker-after-connect-wait: 100
hooks-worker-connect-retry: 500
hooks-worker-connect-timeout: 1500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
hooks-worker-term-retry: 500
hooks-worker-term-timeout: 5000
hooks-worker-timeout: 5000
init: false
inline-errors: false
language: php
loglevel: warning
method: []
names: false
only: []
output: ['test-reports/dredd.xml']
path: []
reporter: ['xunit']
require: null
server: null
server-wait: 3
sorted: false
user: null

